language: php
sudo: false

php:
  - 5.5.9
  - 5.6
  - 7
  - hhvm

env:
  global:
    # The name of the moduel to run tests on (this module).
    - DRUPAL_MODULE=autovalue
    # Database variable for kernel tests.
    - SIMPLETEST_DB="mysql://root:@127.0.0.1/drupal"
    # Web server URL for browser tests.
    - SIMPLETEST_BASE_URL="http://localhost:8888"

matrix:
  allow_failures:
    # We cannot use hhvm-nightly since that does not work in Travis CI's old
    # Ubuntu 12.04.
    - php: hhvm
  # Don't wait for the allowed failures to build.
  fast_finish: true

services:
  - mysql

before_script:
  # Remove Xdebug as we don't need it and it causes
  - phpenv config-rm xdebug.ini || true

  # Create database.
  - mysql -e 'CREATE DATABASE IF NOT EXISTS drupal CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci' -uroot

  # Set the drupal root folder location.
  - export DRUPAL_ROOT=$TRAVIS_BUILD_DIR/../drupal

  # Download Drupal 8 core.
  - travis_retry git clone --branch 8.0.x --depth 1 http://git.drupal.org/project/drupal.git $DRUPAL_ROOT

  # Reference the module in build site.
  - ln -s $TRAVIS_BUILD_DIR $DRUPAL_ROOT/modules/$DRUPAL_MODULE

  # Start a web server on port 8888, run in the background; wait for initialization.
  - nohup php -S localhost:8888 > /dev/null 2>&1 &

script:
  # Run the PHPUnit tests which also include the kernel tests.
  - $DRUPAL_ROOT/vendor/phpunit/phpunit/phpunit -c $DRUPAL_ROOT/core/phpunit.xml.dist --verbose $DRUPAL_ROOT/modules/$DRUPAL_MODULE
